version: '3.8'

services:
    alpine:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: symfony_docker
        restart: on-failure
        ports:
            - "1234:80"
        volumes:
            - ./conf/site.conf:/etc/nginx/http.d/default.conf
            - ./src:/var/www/html

    db:
        image: mariadb:10.8.2
        container_name: mariadb_docker
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: 'password'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_docker
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: password
        networks:
            - acpSymfony

    mercure:
        image: dunglas/mercure
        restart: unless-stopped
        environment:
            # Uncomment the following line to disable HTTPS
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: 'mkjgfdsmlgfjfjdglkfdlkjgflkdjgjdslgkfdlksjgfdsglkfdjslkj'
            MERCURE_SUBSCRIBER_JWT_KEY: 'mkjgfdsmlgfjfjdglkfdlkjgflkdjgjdslgkfdlksjgfdsglkfdjslkj'
            MERCURE_EXTRA_DIRECTIVES:
                cors_origins "http://localhost:5173"
                cors_origins "http://localhost:1234"
        # Uncomment the following line to enable the development mode
        # command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
        ports:
            - "2345:80"
            - "443:443"

volumes:
    db-data:
