<<<<<<< HEAD
lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
    user_identity_field: email
    clock_skew: 0
    allow_no_expiration: false
    encoder:
        service: lexik_jwt_authentication.encoder.lcobucci

        signature_algorithm: RS256
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization

        cookie:
            enabled: false
            name: BEARER

        query_parameter:
            enabled: false
            name: bearer

        split_cookie:
            enabled: false
            cookies:
                - jwt_hp
                - jwt_s
    remove_token_from_body_when_cookies_used: true
=======
lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
>>>>>>> 35256268eabfd7fd6cc253ed2f6883354df2f918
