security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        users_in_memory: { memory: null }
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            custom_authenticator: App\Security\Authenticator
            lazy: true
            provider: app_user_provider
            form_login:
                check_path: app_login
                login_path: app_login
                enable_csrf: true
                default_target_path: app_index
                always_use_default_target_path: true
            logout:
                path: app_logout
                target: app_index
    access_control:
        - { path: ^/admin$, roles: ROLE_ADMIN }
        - { path: ^/chat$, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
