controllers:
    resource: ../src/Controller/
    type: attribute

index:
    path: /
    controller: App\Controller\IndexController::index

register:
    path: /register
    controller: App\Controller\RegistrationController::register

login:
    path: /login
    controller: App\Controller\LoginController::login

logout:
    path: /logout
    controller: App\Controller\LoginController::logout
